### PR TITLE
fix: Fixes incorrect entry points (#175)

### LINKED ISSUE #175: Entry Points broken
screenshot 2019-03-02 at 15 58 59

### PR DESCRIPTION
**Pull request by ChristianKienle**
Fixes #175

### CODE REVIEW

**Comment by bcullman** [comment]
There are is a number of unrelated changes here that if merged will result in poor git history. 

Consider refocusing the changes to just the task at hand, and open other PRs to fix the other issues (they look like lint changes)

**Comment by ChristianKienle** [comment]
So true.

> There are is a number of unrelated changes here that if merged will result in poor git history.
> 
> Consider refocusing the changes to just the task at hand, and open other PRs to fix the other issues (they look like lint changes)

So true. Will do that.

**Comment by ChristianKienle** [comment]
> There are is a number of unrelated changes here that if merged will result in poor git history.
> 
> Consider refocusing the changes to just the task at hand, and open other PRs to fix the other issues (they look like lint changes)

fixes @bcullman

**Comment by ChristianKienle** [comment]
@bcullman can you approve again? :) Somehow your approval disappeared.

**Pull request merged**
