### PR TITLE
chore: Fixes #234 by updating the docs - also includes a fix for the …

### LINKED ISSUE #234: Remove aria-pressed attribute from "normal" buttons
The `aria-pressed` attribute should only be used for buttons that can be toggled on and off. Currently `FdButton` always adds `aria-pressed=false` by default.

### PR DESCRIPTION
**Pull request by ChristianKienle**

### CODE REVIEW

**Comment by ChristianKienle** [comment]
@suwarnoong could you look at this? :)

**Comment by ChristianKienle** [comment]
@suwarnoong @CodesOfRa  Could you look at this? :)

**Comment by CodesOfRa** [comment]
@ChristianKienle Do you have to change the url every time the docs are redeployed ? 
_PS : just out of curiosity :D_

**Comment by ChristianKienle** [comment]
> @ChristianKienle Do you have to change the docs url every time the docs are redeployed ?
> _PS : just out of curiosity :D_

Atm yes. This is a feature. Feature.
However we should probably move to GH Pages...

**Pull request merged**
