### PR TITLE
WIP Counter Component

### PR DESCRIPTION
**Pull request by deepshikha02**
Counter Component is primarily used to show the count of some entity.
This is the initial draft.
Further examples to follow.
QUERY : Can any action be performed on the Counter. If not, there is a bug since the notification counter looks actionable.
(When you hover over it, the cursor gives the finger pointer )
https://sap.github.io/fundamental/components/status-indicators.html

### CODE REVIEW

**Comment by droshev** [comment]
@deepshikha02 would you mind creating some unit tests?

**Comment by xujing-shen** [comment]
Need to have validation for the count, a minimum value 1, maximum display is 999+. 
And input must be integer (I guess)

**Comment by xujing-shen** [comment]
not sure counter with --notification modifier should contains button with sap-icon--bell , or just the span part

**Comment by deepshikha02** [comment]
> not sure counter with --notification modifier should contains button with sap-icon--bell , or just the span part

This is in accordance with the html generated in the fundamental-UI component. 
I have posted a question regarding the design of the control. waiting for the reply.

**Comment by deepshikha02** [comment]
> @deepshikha02 would you mind creating some unit tests?

Unit tests are added.

**Pull request merged**
