### PR TITLE
fix: Fixes Side Nav bug + adds test + brings back the status icons

### PR DESCRIPTION
**Pull request by ChristianKienle**

### CODE REVIEW

**Comment by bcullman** [comment]
There are is a number of unrelated changes here that if merged will result in poor git history.

Consider refocusing the changes to just the task at hand, and open other PRs to fix the other issues (they look like lint changes)

**Comment by ChristianKienle** [comment]
> There are is a number of unrelated changes here that if merged will result in poor git history.
> 
> Consider refocusing the changes to just the task at hand, and open other PRs to fix the other issues (they look like lint changes)

That happens when you branch from your own branch that is not yet merged. :( Will change that.

**Comment by bcullman** [comment]
*always* branch from master.

**Comment by ChristianKienle** [comment]
> _always_ branch from master.

Yeah - this branch required something that was not yet in master but the PR was already open. :)

**Pull request closed without merging**
